CREATE DATABASE ECOMERCE;

USE ECOMERCE;

CREATE TABLE CATEGORIA(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(1000) NULL,
    PARENT_CATEGORIA_ID INT NULL
);

CREATE TABLE PRODUTO(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    CATEGORIA_ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(1000) NULL,
    PRECO NUMERIC(9,2) NULL,
    STOCK VARCHAR(100) NULL,
    SKU INT NULL,
    IMAGEM_URL VARCHAR(100) NULL,
    CONSTRAINT FK_CATEGORIA_PRODUTO foreign key(CATEGORIA_ID)
    REFERENCES CATEGORIA(ID)
);

CREATE TABLE USUARIO(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    CREATED_AT DATETIME NULL DEFAULT NOW(),
    TELEFONE VARCHAR(50) NULL
);

CREATE TABLE ENDERECO(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    USER_ID INT NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CEP VARCHAR(50) NULL,
    TIPO INT NULL,
    PADRAO VARCHAR(100) NULL DEFAULT 'sim',
    CONSTRAINT FK_ENDERECO_USUARIO FOREIGN KEY(USER_ID)
    REFERENCES USUARIO(ID)
);

CREATE TABLE CARRINHO(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    USER_ID INT NOT NULL,
    CREATED_AT DATETIME DEFAULT NOW(),
    UPDATED_AT DATETIME DEFAULT NOW(),
    CONSTRAINT FK_CARRINHO_USUARIO FOREIGN KEY(USER_ID)
    REFERENCES USUARIO(ID)
);

CREATE TABLE ORDEM(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    USER_ID INT NOT NULL,
    DATA DATETIME DEFAULT NOW(),
    TOTAL NUMERIC(9,2) NULL,
    STATUS VARCHAR(50) DEFAULT 'LIVRE',
    CONSTRAINT FK_USUARIO_ORDEM FOREIGN KEY(USER_ID)
    REFERENCES USUARIO(ID)
);

CREATE TABLE ORDEM_ITENS(
    ID INT NOT NULL auto_increment PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    QUANTIDADE SMALLINT NULL DEFAULT 1,
    PRECO NUMERIC(9,2) NULL,
    CONSTRAINT FK_ORDEM_OI FOREIGN KEY(ORDER_ID)
    REFERENCES ORDEM(ID),
    CONSTRAINT FK_PRODUTO_OI FOREIGN KEY(PRODUTO_ID)
    REFERENCES PRODUTO(ID)
);


ALTER TABLE USUARIO
ADD COLUMN CPF VARCHAR(11) NOT NULL UNIQUE;

ALTER TABLE CARRINHO
DROP CONSTRAINT FK_CARRINHO_USUARIO;

DROP TABLE CARRINHO;

INSERT INTO USUARIO
VALUES(0, 'JOAO SILVA', 'JOAO@GMAIL.COM', 'JO123', NOW()
, '7188888', '123456');

INSERT INTO USUARIO(ID, NOME, EMAIL, SENHA, TELEFONE, CPF)
VALUES(0, 'RICARDO SILVA', 'RICARDO@GMAIL.COM', 'RI123', '7188888', '123');


UPDATE USUARIO
    SET NOME = 'JOAO COSTA', EMAIL = 'JS@GMAIL.COM'
    WHERE ID = 1;
   
DELETE FROM CARRINHO
WHERE USER_ID = 1;

UPDATE PRODUTO
    SET PRECO = PRECO + (PRECO * 0.10)
    WHERE ID= 1;

UPDATE PRODUTO
    STOCK = STOCK - 5
    WHERE ID = 1;

UPDATE PAGAMENTO
    SET STATUS = 'CONFIRMADO', AMOUNT = 150
    WHERE ID = 1;

DELETE FROM CARRINHO
WHERE CREATED_AT = '2024-01-01' ;

DELETE FROM CARRINHO WHERE CREATED_AT = '2024-01-01';

DELETE FROM PRODUTO
WHERE SKU = 'OLD-123';

ALTER TABLE PRODUTO
MODIFY COLUMN SKU VARCHAR(50) NULL;


SET SQL_SAFE_UPDATES = 0;

INSERT INTO CATEGORIA
VALUES(0, 'CALÇA', 'JEANS', 0);
SELECT * FROM CATEGORIA;

SELECT * FROM PRODUTO;
INSERT INTO PRODUTO
VALUES(0, 1, 'CAMISA PRETA', 'CAMISA DE MANGA LONGA', 56, 10, 'OLD-123', '');
INSERT INTO PRODUTO
VALUES(0, 1, 'CALÇA PRETA', 'CALÇA JEANS', 150, 10, 'OLD-222', '');

INSERT INTO ORDEM
VALUES(0, 1, NOW(), 0, 'VENDIDO');

INSERT INTO ORDEM_ITENS
VALUES(0, 1, 1, 2, 100);

INSERT INTO ORDEM_ITENS
VALUES(0, 1, 3, 1, 150);

CREATE VIEW VW_RELATORIO
AS
SELECT PRO.NOME AS 'PRODUTO', O.DATA, U.NOME AS 'USUARIO', PRO.PRECO, OI.QUANTIDADE,
        (PRO.PRECO * OI.QUANTIDADE) AS 'TOTAL'
FROM ORDEM_ITENS OI
INNER JOIN PRODUTO PRO ON PRO.ID = OI.PRODUTO_ID
INNER JOIN ORDEM O ON O.ID = OI.ORDER_ID
INNER JOIN USUARIO U ON U.ID = O.USER_ID


SELECT USUARIO, SUM(TOTAL)
FROM VW_RELATORIO
GROUP BY USUARIO;